[features]
seeds = false
skip-lint = false
[programs.localnet]
contract_options = "J85ChLMWGQpRVu9VChUwFrfXnThNQRWho9ot8c4MFbFu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rushikeshghotekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
